version: '3.8'

services:

  main:
    image: ${PJT_DOCKER_NAME:?err}.local

    extends:
      file: .dockyman/profiles/local.yaml
      service: local
  
    env_file:
      - .env

    entrypoint: /var/dockyman/scripts/initContainer.sh
    
    command: bash

    volumes:
      - type: bind
        source: ./workdir
        target: /workdir

      - type: bind
        source: ./scripts
        target: /var/dockyman/scripts