version: '3.8'

services:

  main:
    container_name: ${CONTAINER_NAME}-nvidia

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [graphics,utility]
