version: '3.8'

services:

  main:
    image: ${LOCAL_DOCKER_IMAGE}

    environment:
        - DISPLAY=${DISPLAY}
        - QT_X11_NO_MITSHM=1
        - XAUTHORITY=/home/docky/.Xauthority
        - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
        - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}

    privileged: true
    stdin_open: true
    tty: true
    network_mode: host

    volumes:
      - type: bind
        source: ${XAUTHORITY}
        target: /home/docky/.Xauthority

      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix

      - type: bind
        source: ${XDG_RUNTIME_DIR}/pulse
        target: ${XDG_RUNTIME_DIR}/pulse

      - type: bind
        source: ${XDG_RUNTIME_DIR}/dconf
        target: ${XDG_RUNTIME_DIR}/dconf

      - type: bind
        source: ./workdir
        target: /home/docky/workdir

    container_name: ${CONTAINER_NAME}
