name: AUTO TAG

on:
  schedule:
    - cron:  '0 0 1 * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: set tag name
       id: tag
       run: echo "::set-output name=tag::$(date +'v%Y.%m')"
        
     - name: Create tag
       uses: actions/github-script@v5
       with:
          script: |
                  github.rest.git.createRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: 'refs/tags/${{ steps.tag.outputs.tag }}',
                  sha: context.sha
                  })
