name: AUTO TAG

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set current tag name
        run: echo "TAGNAME::$(date +'v%Y.%m')" >> $GITHUB_ENV

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
                  github.rest.git.createRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: 'refs/tags/$TAGNAME',
                  sha: context.sha
                  })
