name: AUTO TAG

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set current tag name
        uses: actions/github-script@v5
        id: set-tagname
        with:
          script: return "$(date +'v%Y.%m')"
          result-encoding: string

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
                  github.rest.git.createRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: 'refs/tags/${{steps.set-tagname.outputs.result}}',
                  sha: context.sha
                  })
