# This is a basic workflow to help you get started with Actions

name: CD - DOCKER PUSH

on:
  release:
    types:
      - created

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: push
      run: bash .dockyman/build.sh distro
