# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
    - cron:  '0 0 1 * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: set tag name
       id: tag
       run: echo "::set-output name=tag::$(date +'v%Y.%m')"
     
     - name: checkout repo
       uses: actions/checkout@v2

     - name: change release version
       run: |
            git pull origin master
            git checkout master
            git branch ${{ steps.tag.outputs.tag }}
            git checkout ${{ steps.tag.outputs.tag }}
            sed -i -r 's/^(RELEASE=).*/\1${{ steps.tag.outputs.tag }}/' .env
            git config --global user.name 'S4HRI bot'
            git config --global user.email 'your-username@users.noreply.github.com'
            git remote set-url --push origin https://github.com/${{github.repository}}
            git commit -m "Auto versioning" --amend --reset-author
            git push origin ${{ steps.tag.outputs.tag }}
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
     - name: Log in to Docker Hub
       uses: docker/login-action@v1
       with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

     - name: build
       run: bash .dockyman/build.sh

     - name: Create tag
       uses: actions/github-script@v5
       with:
        script: |
                github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'refs/tags/${{ steps.tag.outputs.tag }}',
                sha: context.sha
                })
     - name: Create Pull Request
       uses: peter-evans/create-pull-request@v3
       with:
        commit-message: update release
        title: Update release
        body: Updating version ${{ steps.tag.outputs.tag }}
        branch: ${{ steps.tag.outputs.tag }}

     - name: push
       run: bash .dockyman/build.sh distro
