# This is a basic workflow to help you get started with Actions

name: CI - PULL REQUEST

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: set tag name
       id: tag
       run: echo "::set-output name=tag::$(date +'v%Y.%m')"

     - uses: actions/checkout@v2
       with:
         fetch-depth: 0

     - name: Create Pull Request
       uses: peter-evans/create-pull-request@v3
       with:
         commit-message: update release
         title: Update release
         body: Updating version ${{ steps.tag.outputs.tag }}
         branch: ${{ steps.tag.outputs.tag }}
