# This is a basic workflow to help you get started with Actions

name: CI/CD

on:
  schedule:
    - cron:  '0 0 1 * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: set tag name
       id: tag
       run: echo "::set-output name=tag::$(date +'v%Y.%m')"

     - name: checkout repo
       uses: actions/checkout@v2

     - name: Log in to Docker Hub
       uses: docker/login-action@v1
       with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

     - name: build
       run: |
            git pull origin master
            git checkout master
            sed -i -r 's/^(RELEASE=).*/\1${{ steps.tag.outputs.tag }}/' .env
            bash .dockyman/build.sh
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     - name: commit files
       run: |
            git config --global user.name 'S4HRI bot'
            git config --global user.email 's4hri-bot@users.noreply.github.com'
            git commit -m "Auto versioning" -a

     - name: push changes
       uses: ad-m/github-push-action@master
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         branch: refs/heads/master

     - name: Create tag
       uses: actions/github-script@v5
       with:
        script: |
                github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'refs/tags/${{ steps.tag.outputs.tag }}',
                sha: context.sha
                })

     - name: Create Release
       uses: ncipollo/release-action@v1
       with:
          tag: ${{ steps.tag.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.tag.outputs.tag }}

     - name: docker push
       run: bash .dockyman/build.sh distro
