# This is a basic workflow to help you get started with Actions

name: CI/CD

on:
  schedule:
    - cron:  '0 0 1 * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: set tag name
       id: tag
       run: echo "::set-output name=tag::$(date +'v%Y.%m')"

     - name: checkout repo
       uses: actions/checkout@v2

     - name: change release version
       run: |
            git pull origin master
            git checkout master
            sed -i -r 's/^(RELEASE=).*/\1${{ steps.tag.outputs.tag }}/' .env

     - name: build
       run: bash .dockyman/build.sh

     - name: push release version
       run: |
            git config --global user.name 'S4HRI bot'
            git config --global user.email 's4hri-bot@users.noreply.github.com'
            git remote set-url --push origin https://github.com/${{github.repository}}
            git add .env
            git commit -m "Auto versioning"
            git push origin master
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     - name: Create tag
       uses: actions/github-script@v5
       with:
        script: |
                github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'refs/tags/${{ steps.tag.outputs.tag }}',
                sha: context.sha
                })

     - uses: ncipollo/release-action@v1
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         name: ${{ steps.tag.outputs.tag }}

     - name: Log in to Docker Hub
       uses: docker/login-action@v1
       with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

     - name: push
       run: bash .dockyman/build.sh distro
